### ISSUE TITLE
Change the pod name

### ISSUE THREAD

**Issue by Mayank17M** [MLH-Fellowship/pod-22.P3.1-portfolio#16]
Currently, the website shows Pod's name as Pod 4.1.X
It should be changed to the Pod's new name(Software Simbas).

**Comment by Mayank17M** [comment]
The name should be changed to Software Simbas.

**Comment by Mayank17M** [comment]
@yashika51 can you tag this as a good first issue?

**Comment by EfazAhmed** [comment]
Can I take this issue?

**Comment by Mayank17M** [comment]
Sure, go ahead!

**Comment by EfazAhmed** [comment]
Thank you! :)
