### ISSUE TITLE
Fix Netlify Status badge

### ISSUE THREAD

**Issue by Mayank17M** [MLH-Fellowship/pod-22.P3.1-portfolio#17]
The Netlify status badge in the README file seems to be broken. Also, the deploy link should be updated.

![image](https://user-images.githubusercontent.com/56592363/161750900-94e6c528-f557-4b21-9a56-ac8ecea5bdd6.png)

**Comment by AnushaNathRoy** [comment]
I and my teammate @Aastha2602 will like to take up this issue.

**Comment by Mayank17M** [comment]
So, right now when we click the netlify badge, it redirects to the deploy link of the root directory.
And shows something like this:

![image](https://user-images.githubusercontent.com/56592363/161955406-5b4adcd2-c068-43b0-8bdc-598e7e72714d.png)

The link should be changed to our project's deploy link, then it'll show something like this:

![image](https://user-images.githubusercontent.com/56592363/161955577-9006e097-1f79-4805-8994-de30588a9022.png)

This is the netlify deploy link for our project: https://app.netlify.com/sites/prep-22-p3-1/deploys
