### ISSUE TITLE
Add pod stats

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/pod-22.P3.1-portfolio#4]
Add a way to display the number of contributions between fellows. Make a little leaderboard or similar to motivate people to add new issues!

**Comment by Mutugiii** [comment]
@OmkarAcharekar and I would love to work on this one!

**Comment by Mayank17M** [comment]
Can I work on this? Actually, I started working on this issue but forgot to comment here.

**Comment by Mutugiii** [comment]
@Mayank17M Sure feel free to continue working on it, no problem!
