### ISSUE TITLE
Update the Error Page

### ISSUE THREAD

**Issue by Mutugiii** [MLH-Fellowship/pod-22.P3.1-portfolio#40]
Proposal to upgrade the error page(404.html) to include a button to go back home and possibly other UI enhancements

**Comment by Mutugiii** [comment]
@yashika51 This could be a possible enhancement

**Comment by Mutugiii** [comment]
@OmkarAcharekar and I would love to work on it

**Comment by 1219aks** [comment]
Can I work on this as well? Thank you.
