### ISSUE TITLE
Mobile Responsiveness

### ISSUE THREAD

**Issue by Mutugiii** [MLH-Fellowship/pod-22.P3.1-portfolio#59]
There seems to be some issues with mobile responsiveness, particularly with
- The Navbar
-  Social Profiles(CV) in the Pod Member Cards: Seems to be exceeding the card layout

Also scrolling through the images takes time - Possibly reduce the image sizes and/or align 2 per row

This was done using chrome dev tools and the dimensions of a Samsung Galaxy S8+

https://user-images.githubusercontent.com/48474421/162417980-d6ed4f65-7a2e-4a23-b2b6-61a82a581847.mp4

**Comment by OmkarAcharekar** [comment]
May be we can hide the images .. They take too much time to scroll to the bottom on mobile
